---
title: "p8105_hw1_mw3845"
author: "Minghe Wang"
date: "2024-09-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1

```{r load dataset penguins}
data("penguins", package = "palmerpenguins")
```

The dataset `penguins` contains 8 variables including `species`, `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`, `sex`, `year`. This dataset has `r nrow(penguins)` rows and `r ncol(penguins)` columns. The mean of `flipper_length_mm` is `r mean(penguins$flipper_length_mm, na.rm=TRUE)`.

```{r scatterplot_flipperLength_vs_billLength}
plot_df = tibble(
  x = penguins$bill_length_mm,
  y = penguins$flipper_length_mm
)

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + 
  geom_point() +
  labs(title = "Bill length(mm) vs Flipper length(mm)")

ggsave('bill vs flipper.png')
```
## Problem 2

Generating dataframe containing different types of variables.
```{r generate 4x10 dataframe}
set.seed(123)

standard_normal_vec = rnorm(10, mean = 0, sd = 1)
positive_logical_vec = standard_normal_vec > 0
character_vec = c('milk', 'cheese', 'egg', 'banana', 'apple', 'toast', 'orange juice', 'peanut butter', 'cucumber',  'coffee')
factor_vec = factor(sample(c('low', 'medium', 'high'), size = 10, replace = TRUE))

df = data.frame(
  standard_normal_var = standard_normal_vec,
  positive_logical_var = positive_logical_vec,
  character_var = character_vec,
  factor_var = factor_vec
)
```
